Vagrant.configure("2") do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  config.vm.provider "docker" do |d|
    d.image = "vorlock/debian-sid"
    d.has_ssh = true
    d.volumes = ["/home/dev"]
  end
end
